name: Application Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run tests & coverage
        run: yarn test:coverage
