name: Application Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: "yarn"

      - name: Pre Deploy
        run: yarn predeploy

      - name: Deploy
        run: yarn deploy
